FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
RUN pip install --upgrade pip setuptools

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /code

# RUN sqlacodegen_v2 --schema identity,payment,shared  mssql+pymssql://SA:reallyStrongPwd123@172.17.0.3:1433/Pendo.Database > /code/app/src/PendoDatabase.py

CMD ["fastapi", "run", "/code/main.py", "--port", "8000"]