version: '3.8'
services:
  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    networks:
      - kong-net

networks:
  kong-net:
    external: true
