# 
# Dockerfile FastAPI image for Pendo.MessageService
# Author: Alexander McCall
# Created: 12/02/2025
#
FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./message_docker_env /code/message_docker_env

CMD ["pytest"]