version: '3.8'
services:
  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    networks:
      - test_net

  message-test-client:
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - message-service
    networks:
      - test_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - TEST_GATEWAY=${ENABLE_GATEWAY:-false}  # Use environment variable if set, default to false

  # Gateway test profile
  message-test-client-gateway:
    profiles:
      - gateway
    build: 
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - message-service
    networks:
      - test_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - TEST_GATEWAY=true

networks:
  test_net:
    driver: bridge
