FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY test-requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -r test-requirements.txt

COPY . .

CMD ["pytest", "tests/"]
