# Docker Compose for Message Service with Kong Gateway
# No version field (newer Docker Compose doesn't require it)
services:
  kong:
    build:
      context: ./Pendo.ApiGateway
      dockerfile: Dockerfile
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug
    volumes:
      - ./Pendo.ApiGateway/kong/declarative:/usr/local/kong/declarative
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - pendo-network

  message-service:
    image: python:3.9-slim
    container_name: message-service
    volumes:
      - ./Pendo.MessageService:/app
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt &&
               python -m src.app"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - KONG_GATEWAY_URL=http://kong-gateway:8000
      - SERVICE_NAME=message-service
      - WS_PORT=5006
      - HTTP_PORT=5007
      # For local testing of Azure-like environment 
      # - BEHIND_TLS_PROXY=true
    ports:
      - "5006:5006"
      - "5007:5007"
    depends_on:
      - kong
    networks:
      - pendo-network

networks:
  pendo-network:
    driver: bridge
