version: '3.8'
services:
  kong:
    image: kong:2.8.3
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_GUI_PATH: /
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      # WebSocket configuration - use standard Nginx directives instead
      KONG_NGINX_HTTP_PROXY_READ_TIMEOUT: 3600s
      KONG_NGINX_HTTP_PROXY_SEND_TIMEOUT: 3600s
      KONG_NGINX_HTTP_KEEPALIVE_TIMEOUT: 65s
    volumes:
      - ../Pendo.ApiGateway/kong/declarative:/usr/local/kong/declarative
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8443:8443"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - kong-net

  message-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5006/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  message-test-client:
    build: 
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5059:5007"  # Map host port 5059 to container port 5007 to avoid conflict
    depends_on:
      - message-service
    networks:
      - kong-net
    environment:
      - PYTHONUNBUFFERED=1
      - TEST_GATEWAY=true
      - HOST_PORT=5059  # Update this to match the new external port

networks:
  kong-net:
    driver: bridge
