# 
# Dockerfile FastAPI image for Pendo.JourneyService
# Author: Alexander McCall
# Created: 12/02/2025
#

FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /code/app

CMD ["fastapi", "run", "app/src/journey_service.py", "--port", "5002"]