// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Identity.DataAccess.Models;

public partial class ApiClient
{
    public int ApiClientId { get; set; }

    public string ApiName { get; set; }

    public string ClientId { get; set; }

    public string ClientSecret { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }
}