// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Identity.DataAccess.Models;

public partial class Configuration
{
    public Guid ConfigurationId { get; set; }

    public string Key { get; set; }

    public string Value { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }
}