// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Identity.DataAccess.Models;

public partial class OtpLogin
{
    public Guid OtpLoginId { get; set; }

    public Guid UserId { get; set; }

    public string CodeHash { get; set; }

    public DateTime IssueDate { get; set; }

    public DateTime ExpiryDate { get; set; }

    public bool Verified { get; set; }

    public virtual User User { get; set; }
}