// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Identity.DataAccess.Models;

public partial class PendoDatabaseContext : DbContext
{
    public PendoDatabaseContext(DbContextOptions<PendoDatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Configuration> Configuration { get; set; }

    public virtual DbSet<OtpLogin> OtpLogin { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserType> UserType { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Configuration>(entity =>
        {
            entity.HasKey(e => e.ConfigurationId).HasName("PK__Configur__95AA53BBF4B673D6");

            entity.ToTable("Configuration", "shared");

            entity.HasIndex(e => e.Key, "UQ__Configur__C41E0289E137EECA").IsUnique();

            entity.Property(e => e.ConfigurationId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Key)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UpdateDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Value).IsRequired();
        });

        modelBuilder.Entity<OtpLogin>(entity =>
        {
            entity.HasKey(e => e.OtpLoginId).HasName("PK__OtpLogin__C597BB312DD4267C");

            entity.ToTable("OtpLogin", "identity");

            entity.HasIndex(e => e.UserId, "IX_OtpLogin_UserId");

            entity.Property(e => e.OtpLoginId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CodeHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.HashSalt)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.User).WithMany(p => p.OtpLogin)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OtpLogin_User");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4C9BA5FE5B");

            entity.ToTable("User", "identity");

            entity.HasIndex(e => e.UserTypeId, "IX_User_UserType");

            entity.HasIndex(e => e.Email, "UQ__User__A9D105341E761372").IsUnique();

            entity.Property(e => e.UserId).HasDefaultValueSql("(newsequentialid())");
            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FirstName).HasMaxLength(255);
            entity.Property(e => e.LastName).HasMaxLength(255);
            entity.Property(e => e.UpdateDate).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.UserRating).HasDefaultValue(-1.0);

            entity.HasOne(d => d.UserType).WithMany(p => p.User)
                .HasForeignKey(d => d.UserTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_UserType");
        });

        modelBuilder.Entity<UserType>(entity =>
        {
            entity.HasKey(e => e.UserTypeId).HasName("PK__UserType__40D2D816692AEBEE");

            entity.ToTable("UserType", "identity");

            entity.Property(e => e.Description).HasMaxLength(100);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}