// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Identity.DataAccess.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public double UserRating { get; set; }

    public int UserTypeId { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public virtual ICollection<OtpLogin> OtpLogin { get; set; } = new List<OtpLogin>();

    public virtual UserType UserType { get; set; }
}