// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Identity.DataAccess.Models;

public partial class UserType
{
    public int UserTypeId { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ICollection<User> User { get; set; } = new List<User>();
}