_format_version: "2.1"
_transform: true

services:
  - name: message-service
    url: https://message-service.greensand-8499b34e.uksouth.azurecontainerapps.io
    protocol: https
    routes:
      - name: message-ws-route
        protocols:
          - http
          - https
        paths:
          - /message/ws
        strip_path: false
        headers:
          Upgrade:
            - websocket
          Connection:
            - Upgrade
        methods:
          - GET
          - OPTIONS
        preserve_host: false
      - name: message-websocket-direct
        protocols:
          - http
          - https
        paths:
          - /ws
        strip_path: false
        headers:
          Upgrade:
            - websocket
          Connection:
            - Upgrade
        methods:
          - GET
          - OPTIONS
        preserve_host: false
    # Other routes...
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Accept
            - Authorization
            - Content-Type
            - Upgrade
            - Connection
          exposed_headers:
            - Authorization
          credentials: true
          max_age: 3600
