# 
# Dockerfile Pytest image for Pendo.PaymentService
# Author: Alexander McCall
# Created: 12/02/2025
#

FROM python:3.9-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /code/app

CMD ["pytest"]