# 
# Dockerfile Pytest image for Pendo.PaymentService
# Author: Alexander McCall
# Created: 12/02/2025
#

FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./app /app

CMD ["pytest"]