/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/home/settings`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/book`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/chat`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/profile`; params?: Router.UnknownInputParams; } | { pathname: `/home/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/home/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/home/tabs/book`; params?: Router.UnknownOutputParams; } | { pathname: `/home/tabs/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/home/tabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/home/tabs/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/home/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/sign-up${`?${string}` | `#${string}` | ''}` | `/auth/welcome${`?${string}` | `#${string}` | ''}` | `/home/settings${`?${string}` | `#${string}` | ''}` | `/home/tabs/book${`?${string}` | `#${string}` | ''}` | `/home/tabs/chat${`?${string}` | `#${string}` | ''}` | `/home/tabs/home${`?${string}` | `#${string}` | ''}` | `/home/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/auth/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/home/settings`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/book`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/chat`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/home/tabs/profile`; params?: Router.UnknownInputParams; } | `/home/chat/${Router.SingleRoutePart<T>}` | { pathname: `/home/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
