name: CI-Database

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Pendo.Database/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build SQL Project
      working-directory: ./Pendo.Database
      run: dotnet build -c Release

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_SQL }}

    - name: Deploy Database
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        database-name: Pendo.Database
        path: './Pendo.Database/bin/Release/Pendo.Database.dacpac'
        action: 'publish'
