name: CI-Database

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Pendo.Database/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: 'true'
  
    - name: Publish database
      run: |
        sqlpackage /Action:Publish /TargetConnectionString:"Server=tcp:pendolare.database.windows.net,1433;Initial Catalog=Pendolare.Database;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Default;" /SourceFile:Pendo.Database/bin/Release/Pendo.Database.dacpac /p:DropObjectsNotInSource=true

    - name: Install SQLPackage
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -O sqlpackage.zip https://aka.ms/sqlpackage-linux
        unzip sqlpackage.zip -d sqlpackage
        chmod +x sqlpackage/sqlpackage
        sudo mv sqlpackage/sqlpackage /usr/local/bin/sqlpackage

    - name: Build Database Project
      run: dotnet build ./Pendo.Database/Pendo.Database.sqlproj -c Release

    - name: Publish Database
      run: |
        /usr/local/bin/sqlpackage \
          /Action:Publish \
          /TargetConnectionString:"${{ secrets.AZURE_SQL_CONNECTION_STRING }}" \
          /SourceFile:"Pendo.Database/bin/Release/Pendo.Database.dacpac" \
          /p:DropObjectsNotInSource=true
