name: CI-Database

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Pendo.Database/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install SQLPackage
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        wget -O sqlpackage.zip https://aka.ms/sqlpackage-linux
        unzip sqlpackage.zip -d sqlpackage
        chmod +x sqlpackage/sqlpackage
        sudo mv sqlpackage/sqlpackage /usr/local/bin/sqlpackage
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: 'true'

    - name: Deploy Database
      uses: azure/sql-action@v2.3
      with:
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        path: './Pendo.Database/Pendo.Database.sqlproj'
        action: 'publish'
        build-arguments: '-c Release'
        arguments: '/p:DropObjectsNotInSource=true'
