name: SonarCloud PR Analysis

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for detecting changes
          
      - name: Get changed directories
        id: changed-dirs
        run: |
          CHANGES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -oE "^Pendo\.[^/]+" | sort -u)
          echo "Changed directories: $CHANGES"
          echo "::set-output name=dirs::$CHANGES"

      - name: Detect project types
        id: set-matrix
        run: |
          MATRIX="{\"include\":["
          FIRST=true
          for DIR in ${{ steps.changed-dirs.outputs.dirs }}; do
            if [ -f "$DIR/*.csproj" ]; then
              TYPE="dotnet"
            elif [ -f "$DIR/package.json" ]; then
              TYPE="node"
            elif [ -f "$DIR/requirements.txt" ]; then
              TYPE="python"
            else
              continue
            fi
            
            if [ "$FIRST" = true ]; then
              FIRST=false
            else
              MATRIX="${MATRIX},"
            fi
            
            MATRIX="${MATRIX}{\"directory\":\"$DIR\",\"type\":\"$TYPE\"}"
          done
          MATRIX="${MATRIX}]}"
          echo "::set-output name=matrix::$MATRIX"

  sonarcloud:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-changes.outputs.matrix)}}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Setup .NET
    - name: Setup .NET
      if: matrix.type == 'dotnet'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    # Setup Node.js
    - name: Setup Node.js
      if: matrix.type == 'node'
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Setup Python
    - name: Setup Python
      if: matrix.type == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Install dependencies based on project type
    - name: Install .NET dependencies
      if: matrix.type == 'dotnet'
      working-directory: ${{ matrix.directory }}
      run: dotnet restore

    - name: Install Node.js dependencies
      if: matrix.type == 'node'
      working-directory: ${{ matrix.directory }}
      run: npm install

    - name: Install Python dependencies
      if: matrix.type == 'python'
      working-directory: ${{ matrix.directory }}
      run: pip install -r requirements.txt

    # Run SonarCloud analysis based on project type
    - name: SonarCloud .NET analysis
      if: matrix.type == 'dotnet'
      working-directory: ${{ matrix.directory }}
      run: |
        dotnet sonarscanner begin /k:"pendo_${{ matrix.directory }}" /d:sonar.login=${{ secrets.SONAR_TOKEN }}
        dotnet build
        dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud Node.js analysis
      if: matrix.type == 'node'
      working-directory: ${{ matrix.directory }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=pendo_${{ matrix.directory }} \
          -Dsonar.sources=. \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud Python analysis
      if: matrix.type == 'python'
      working-directory: ${{ matrix.directory }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=pendo_${{ matrix.directory }} \
          -Dsonar.sources=. \
          -Dsonar.python.version=3.9 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
