name: Deploy Identity Service to Azure

on:
  pull_request:
    branches: 
      - main
      - dev
      - infrastructure/kong-integration
    paths:
      - 'Pendo.IdentityService/**'
      - 'infrastructure/**'
  workflow_dispatch:

env:
  ACR_NAME: pendocontainerregistry
  IDENTITY_SERVICE_IMAGE_NAME: pendo-identity-service
  RESOURCE_GROUP: dev
  CONTAINER_APP_NAME: pendo-identity-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: '0a6d7ce5-4951-4af8-932a-94714dd9e70b'
        tenant-id: '0adc3547-e686-4727-9a4c-0c5bb6699047'
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # Get Kong Gateway FQDN for service integration - make it optional
    - name: Get Kong Gateway FQDN
      id: kong_fqdn
      continue-on-error: true
      run: |
        KONG_FQDN=$(az containerapp show --name kong-gateway --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || echo "")
        if [ -n "$KONG_FQDN" ]; then
          echo "KONG_GATEWAY_FQDN=$KONG_FQDN" >> $GITHUB_ENV
          echo "KONG_EXISTS=true" >> $GITHUB_ENV
          echo "::set-output name=fqdn::$KONG_FQDN"
          echo "::set-output name=exists::true"
        else
          echo "Kong Gateway does not exist yet or could not be accessed"
          echo "KONG_EXISTS=false" >> $GITHUB_ENV
          echo "::set-output name=exists::false"
        fi

    # Build and push the Identity Service image
    - name: Build and push image to ACR
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: |
        docker login ${{ env.ACR_NAME }}.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
        cd Pendo.IdentityService
        docker build . -f ./Pendo.IdentityService.Api/Dockerfile -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IDENTITY_SERVICE_IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IDENTITY_SERVICE_IMAGE_NAME }}:${{ github.sha }}
        docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IDENTITY_SERVICE_IMAGE_NAME }}:${{ github.sha }} ${{ env.ACR_NAME }}.azurecr.io/${{ env.IDENTITY_SERVICE_IMAGE_NAME }}:latest
        docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IDENTITY_SERVICE_IMAGE_NAME }}:latest

    # Deploy the Identity Service - simplified approach using direct parameter passing
    - name: Deploy Container App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Create basic parameters file
          echo "{}" > params.json
          
          # Deploy with each parameter separately
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file infrastructure/identity-service.bicep \
            --parameters containerAppName=${{ env.CONTAINER_APP_NAME }} \
            --parameters containerAppEnvironmentName=pendo-env-dev \
            --parameters registryName=${{ env.ACR_NAME }} \
            --parameters registryUsername=${{ secrets.ACR_USERNAME }} \
            --parameters registryPassword='${{ secrets.ACR_PASSWORD }}' \
            --parameters dbConnectionString='${{ secrets.AZURE_SQL_CONNECTION_STRING }}' \
            --parameters kongGatewayFqdn='${{ steps.kong_fqdn.outputs.fqdn }}'
    
    # Wait for identity service to be ready
    - name: Wait for service to be ready
      run: |
        echo "Waiting for identity-service to be ready..."
        sleep 30

    # Get Identity Service FQDN
    - name: Get Identity Service FQDN
      id: identity_fqdn
      continue-on-error: true
      run: |
        IDENTITY_FQDN=$(az containerapp show --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || echo "")
        if [ -n "$IDENTITY_FQDN" ]; then
          echo "IDENTITY_SERVICE_FQDN=$IDENTITY_FQDN" >> $GITHUB_ENV
          echo "IDENTITY_EXISTS=true" >> $GITHUB_ENV
          echo "::set-output name=fqdn::$IDENTITY_FQDN"
          echo "::set-output name=exists::true"
        else
          echo "Identity Service does not exist yet or could not be accessed"
          echo "IDENTITY_EXISTS=false" >> $GITHUB_ENV
          echo "::set-output name=exists::false"
        fi
    
    # Update Kong configuration if necessary
    - name: Update Kong configuration with Identity Service FQDN
      if: env.KONG_EXISTS == 'true' && env.IDENTITY_EXISTS == 'true'
      run: |
        echo "Both services exist - updating Kong configuration"
        # Install yq
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
        
        # Create a new branch
        git checkout -b update-identity-service-fqdn-${{ github.run_id }}
        
        # Update only the Identity Service URL
        IDENTITY_FQDN="${{ steps.identity_fqdn.outputs.fqdn }}"
        KONG_CONFIG_PATH="Pendo.ApiGateway/kong/declarative/kong-azure.yml"
        
        echo "Updating Identity Service FQDN to: $IDENTITY_FQDN"
        yq -i '.services[] |= select(.name == "identity-service").url = "https://'"$IDENTITY_FQDN"'"' $KONG_CONFIG_PATH
        
        # Only commit if there are changes
        if git diff --quiet $KONG_CONFIG_PATH; then
          echo "No changes needed to Kong configuration"
          exit 0
        fi
        
        # Commit changes and create PR
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add $KONG_CONFIG_PATH
        git commit -m "Update Identity Service FQDN to $IDENTITY_FQDN"
        git push -u origin update-identity-service-fqdn-${{ github.run_id }}
        
        # Create a pull request
        PR_TITLE="Update Identity Service FQDN from CI/CD"
        PR_BODY="This PR updates the Kong Gateway config with the latest Identity Service FQDN ($IDENTITY_FQDN)"
        PR_DATA="{\"title\":\"$PR_TITLE\",\"body\":\"$PR_BODY\",\"head\":\"update-identity-service-fqdn-${{ github.run_id }}\",\"base\":\"infrastructure/kong-integration\"}"
        
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "$PR_DATA" \
          https://api.github.com/repos/${{ github.repository }}/pulls
