name: Pendo-PaymentService
description: "Build and test the Payment Service project"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.PaymentService/**'
      - '.github/workflows/Pendo.PaymentService.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ./Pendo.PaymentService
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Move Configuration File to Correct Location
      working-directory: ./Pendo.PaymentService
      run: |
        mkdir app/code/src/configuration/ -p
        cp ./app/src/configuration/appsettings.development.json ./app/code/src/configuration/appsettings.development.json

    - name: Test project
      working-directory: ./Pendo.PaymentService/app
      run: pytest --junitxml=payment_test_results.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ./Pendo.PaymentService/app/payment_test_results.xml