name: Pendo-JourneyService
description: "Build and test the Journey Service project"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.JourneyService/**'
      - '.github/workflows/Pendo.JourneyService.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ./Pendo.JourneyService
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test project
      working-directory: ./Pendo.JourneyService
      run: pytest --junitxml=journey_test_results.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: JourneyService Test Results
        files: ./Pendo.JourneyService/journey_test_results.xml