name: Pendo-MessageService
description: "Build and test the Message Service project"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.MessageService/**'
      - '.github/workflows/Pendo.MessageService.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./Pendo.MessageService
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt

    - name: Test project
      working-directory: ./Pendo.MessageService
      run: pytest -xvs tests/ --cov=src --cov-report=term-missing --junitxml=message_test_results.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: Message Service Test Results
        files: ./Pendo.MessageService/message_test_results.xml