name: Pendo-Database
description: "Build database project"

on:
  pull_request:
    branches: [ main, dev ]
    #paths:
    #  - 'Pendo.Database/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install SQLPackage
      run: dotnet tool install -g microsoft.sqlpackage

    - name: Build project
      working-directory: ./Pendo.Database
      run: dotnet build --configuration Release
