name: Pendo-AdminService
description: "Build and test the Admin Service project"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.AdminService/**'
      - '.github/workflows/Pendo.AdminService.yml'
  push:
    branches: [ main, dev ]
    paths:
      - 'Pendo.AdminService/**'
      - '.github/workflows/Pendo.AdminService.yml'
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WF_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        working-directory: ./Pendo.AdminService
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test project
        working-directory: ./Pendo.AdminService
        run: pytest --junitxml=admin_test_results.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: AdminService Test Results
          files: ./Pendo.AdminService/admin_test_results.xml

      - name: Upload Test Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: admin-test-results
          path: ./Pendo.AdminService/admin_test_results.xml