name: Pendo-ApiGateway
description: "Build and test the ApiGateway Kong plugin"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.ApiGateway/**'
      - '.github/workflows/Pendo.ApiGateway.yml'
  push:
    branches: [ main, dev ]
    paths:
      - 'Pendo.ApiGateway/**'
      - '.github/workflows/Pendo.ApiGateway.yml'
      - 'scripts/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WF_PAT }}

      - name: Install Base Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl build-essential lua5.1 dnsutils

      - name: Download and Install Kong
        run: |
          wget https://download.konghq.com/gateway-3.4.x-ubuntu-amd64/pool/all/k/kong/kong_3.4.0_amd64.deb -O kong-3.4.0.deb
          sudo dpkg -i kong-3.4.0.deb || sudo apt-get -f install -y

      - name: Install Luarocks and Busted
        run: |
          sudo apt-get install -y luarocks
          sudo luarocks install busted

      - name: Run Kong plugin tests
        working-directory: ./Pendo.ApiGateway
        run: |
          chmod +x ./spec/run.sh
          ./spec/run.sh

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: ApiGateway Test Results
          files: ./Pendo.ApiGateway/apigateway_test_results.xml

      - name: Upload Test Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apigateway-test-results
          path: ./Pendo.ApiGateway/apigateway_test_results.xml

  update_wiki:
    needs: build_test
    if: always() && github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    concurrency:
      group: wiki-update-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WF_PAT }}
          fetch-depth: 0
          ref: ${{ github.ref}}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Download Test Results Artifact
        uses: actions/download-artifact@v4
        with:
          name: apigateway-test-results
          path: ./Pendo.ApiGateway

      - name: Update Wiki
        run: |
          chmod +x ./scripts/parse-unittests.py
          python ./scripts/parse-unittests.py \
            --service ApiGateway \
            --report ./Pendo.ApiGateway/apigateway_test_results.xml \
            --wiki-file wiki/Tests.md

      - name: Commit Wiki Update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git diff --quiet || (
            git add wiki/Tests.md
            git commit -m "AUTO COMMIT: update ApiGateway test list"
            echo "Wiki updated, pushing changes..."
            git push
          )
