name: Pendo-BookingService
description: "Build and test the Booking Service project"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.BookingService/**'
      - '.github/workflows/Pendo.BookingService.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      working-directory: ./Pendo.BookingService
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    - name: Test project with coverage
      working-directory: ./Pendo.BookingService
      run: pytest --cov=. --cov-report=xml --cov-report=term --junitxml=booking_test_results.xml

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ./Pendo.BookingService/booking_test_results.xml
        
    - name: Post Coverage Comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./Pendo.BookingService/coverage.xml
        junitxml-path: ./Pendo.BookingService/booking_test_results.xml
