name: Pendo-IdentityService
description: "Build and test the Identity Service project"

on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'Pendo.IdentityService/**'
      - '.github/workflows/Pendo.IdentityService.yml'
  push:
    branches: [ main, dev ]
    paths:
      - 'Pendo.IdentityService/**'
      - '.github/workflows/Pendo.IdentityService.yml'
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WF_PAT }}

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        working-directory: ./Pendo.IdentityService
        run: dotnet build --configuration Release

      - name: Test project
        working-directory: ./Pendo.IdentityService
        run: dotnet test --configuration Release --logger "trx;LogFileName=identity_test_results.trx" --results-directory ./Identity.Tests/TestResults

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: IdentityService Test Results
          files: ./Pendo.IdentityService/Identity.Tests/TestResults/identity_test_results.trx

      - name: Upload Test Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: identityservice-test-results
          path: ./Pendo.IdentityService/Identity.Tests/TestResults/identity_test_results.trx