name: Publish wiki

on:
  push:
    branches: [main]
    paths:
      - '**/README.md'  # Track README changes in all subdirectories
      - .github/workflows/publish-wiki.yml

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full repo history is available

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Prepare Wiki Files
        run: |
          mkdir -p wiki  # Ensure wiki directory exists

          # Create Home.md with categories
          echo "# Services" > wiki/Home.md
          echo "" >> wiki/Home.md
          echo "## Home" >> wiki/Home.md
          echo "" >> wiki/Home.md
          echo "## Frontend Software" >> wiki/Home.md
          echo "" >> wiki/Home.md
          echo "## Backend Software" >> wiki/Home.md
          echo "" >> wiki/Home.md

          # Define frontend services
          FRONTEND_SERVICES=("Pendo.AdminDashboard" "Pendo.ClientApp")

          # Find all README.md files excluding the wiki folder itself
          find . -type f -path '*/README.md' ! -path "./wiki/*" | while read file; do
            folder_name=$(dirname "$file" | sed 's|./||')  # Extract folder path
            base_name=$(basename "$folder_name")  # Extract the last folder name
            
            # Ensure 'Pendo.' is added only once
            if [[ "$base_name" != Pendo.* ]]; then
              formatted_name="Pendo.$base_name"
            else
              formatted_name="$base_name"
            fi

            new_file="wiki/${formatted_name}.md"
            cp "$file" "$new_file"

            # Format the wiki link with correct repo details
            wiki_link="https://github.com/COMP2913-24-25/software-engineering-project-team-2/wiki/${formatted_name}"

            # Categorize properly
            if [[ "$folder_name" == wiki/* ]]; then
              echo "- [${formatted_name}](${wiki_link})" >> wiki/Home.md
            elif [[ " ${FRONTEND_SERVICES[@]} " =~ " ${base_name} " ]]; then
              echo "- [${formatted_name}](${wiki_link})" >> wiki/Home.md
            else
              echo "- [${formatted_name}](${wiki_link})" >> wiki/Home.md
            fi
          done

      - name: Debug Wiki Structure
        run: ls -R wiki  # Check the wiki folder structure

      - name: Publish Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki  # Ensure this points to your wiki directory
