name: Publish Wiki

on:
  push:
    branches: [master]
    paths:
      - "wiki/**"
      - ".github/workflows/publish-wiki.yml"

concurrency:
  group: publish-wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq for JSON processing
        run: sudo apt-get install -y jq

      - name: Find all README files (excluding wiki/api-routes)
        id: find_readmes
        run: |
          find . -type f -name "README.md" ! -path "./wiki/api-routes/*" > readmes.txt

      - name: Format README files for Wiki
        run: |
          mkdir -p formatted_readmes
          while read -r file; do
            filename=$(basename "$(dirname "$file")")  # Extracts directory name
            formatted_name=$(echo "$filename" | sed -E 's/([a-z])([A-Z])/\1 \2/g') # Convert CamelCase to spaces
            mv "$file" "formatted_readmes/pendo.${filename}.md"
          done < readmes.txt

      - name: Convert API routes JSON to Markdown
        run: |
          mkdir -p formatted_api
          for jsonfile in wiki/api-routes/*.json; do
            servicename=$(basename "$jsonfile" .json)
            markdownfile="formatted_api/pendo.${servicename}.md"

            echo "# ${servicename} API Routes" > "$markdownfile"
            echo "" >> "$markdownfile"
            echo "| Method  | Endpoint                  | Summary                                      |" >> "$markdownfile"
            echo "|---------|---------------------------|----------------------------------------------|" >> "$markdownfile"

            jq -r '
              .paths as $paths |
              to_entries[] |
              .key as $endpoint |
              .value | to_entries[] |
              [ .key, $endpoint, .value.summary // "No summary provided" ] |
              @tsv
            ' "$jsonfile" | while IFS=$'\t' read -r method endpoint summary; do
              echo "| \`$method\`  | **$endpoint**   | $summary |" >> "$markdownfile"
            done
          done

      - name: Upload Wiki content
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: formatted_readmes
          strategy: normal
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload API Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: formatted_api
          strategy: normal
          token: ${{ secrets.GITHUB_TOKEN }}
